
-- varchar 2 funciona mejor
DROP TABLE PELICULA17;

CREATE TABLE PELICULA17 (
    TITULO VARCHAR2(20) NOT NULL PRIMARY KEY, 
    DIRECTOR VARCHAR2(20),
    TIPO VARCHAR2(20), 
    FECHAESTRENO DATE
);

-- clic derecho en Tables para crear una tabla por GUI

DROP TABLE ACTORES17; -- Igual en en MySQL

CREATE TABLE ACTORES17(
    NUMIDENT NUMBER PRIMARY KEY,
    NUMOSCAR NUMBER, 
    PAIS VARCHAR2(32),
    NOMBRE VARCHAR2(32)
);

DROP TABLE PELACT17; 

CREATE TABLE PELACT17 ( 
    TITULO VARCHAR(20) NOT NULL, 
    NUMIDENT NUMBER NOT NULL,
    FOREIGN KEY (TITULO) REFERENCES PELICULA17(TITULO) ON DELETE CASCADE,
    FOREIGN KEY (NUMIDENT) REFERENCES ACTORES17(NUMIDENT) ON DELETE CASCADE,
    UNIQUE (TITULO, NUMIDENT)
);

-- 2 Comprobacion de las restricciones de integridad
INSERT INTO PELACT17 VALUES (NULL, NULL);
INSERT INTO PELACT17 VALUES (NULL, 1234);
INSERT INTO PELACT17 VALUES ("EMA", NULL);
INSERT INTO PELACT17 VALUES ("DISCO", 1234);

-- 3 Insertar datos en la base de datos
INSERT INTO PELICULA17(TITULO, DIRECTOR, TIPO, FECHAESTRENO)
    VALUES ('EMA', 'Pablo Larrain', 'Drama', '22-SEP-2019'); 
INSERT INTO PELICULA17(TITULO, DIRECTOR, TIPO, FECHAESTRENO)
    VALUES ('DISCO', 'Jorunn Myklebust', 'Drama', '23-SEP-2019');

INSERT INTO ACTORES17 (NUMIDENT, NUMOSCAR, PAIS, NOMBRE)
    VALUES (1234, 0, 'Paola Giannini', 'Italia');
INSERT INTO ACTORES17 (NUMIDENT, NUMOSCAR, PAIS, NOMBRE)
    VALUES (1235, 0, 'Joserfine Frida', 'Chile');

INSERT INTO PELACT17 ( TITULO, NUMIDENT)
    VALUES('EMA', 1234);
INSERT INTO PELACT17 ( TITULO, NUMIDENT)
    VALUES('DISCO', 1235);

COMMIT;

-- 4 Comprobar borrado en cascada 
SELECT * FROM PELICULA17;
DELETE FROM PELICULA17 WHERE TITULO = 'EMA';
SELECT * FROM PELICULA17;
SELECT * FROM PELACT17;

SELECT * FROM ACTORES17;
DELETE FROM ACTORES17 WHERE NUMIDENT = 1235;
SELECT * FROM ACTORES17;
SELECT * FROM PELACT17;

-- 6 
CREATE VIEW V6 AS 
    SELECT NOMBRE, NUMIDENT FROM ACTORES17
    WHERE NUMIDENT < 2000;
SELECT * FROM V6;

-- 7

-- 8
DROP TABLE PELICULA17;
DROP TABLE ACTORES17;
DROP TABLE PELACT17;